name: Python Package Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11","3.12.0-alpha.4"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest coverage
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --exit-zero
      - name: test and cover
        run: |
          coverage run -m pytest
          coverage report --format text
